"use client";
const products=[
{id:"takat-power-x",name:"TAKAT POWER X",detail:"150g bottle",cod:"₹999",online:"₹899.10"},
{id:"max-x7-x100-combo",name:"MAX X7 Capsule + MAX X100 Oil Combo",detail:"30 capsules + oil",cod:"₹2,500",online:"₹1,499"}
];
export default function Home(){return <main className="cleanSite">
<style>{`.cleanSite{font-family:Arial,sans-serif;background:#f8f9f7;color:#17312b;min-height:100vh}.cleanSite *{box-sizing:border-box}.cleanHeader{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:20px max(24px,calc((100vw - 1100px)/2));background:#123b32;color:#fff}.cleanHeader a{color:inherit;text-decoration:none}.cleanBrand{font-weight:900;font-size:1.25rem}.cleanBrand span{font-weight:400}.cleanHeader nav{display:flex;gap:18px;flex-wrap:wrap}.cleanHero,.cleanSection{max-width:1100px;margin:auto;padding:64px 24px}.cleanHero{display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:36px}.cleanHero h1{font-size:clamp(2.2rem,5vw,4rem);margin:12px 0}.cleanHero p,.cleanDetails p,.cleanCard p{font-size:1rem;line-height:1.7}.cleanButton{display:inline-block;background:#123b32;color:#fff!important;text-decoration:none;padding:13px 22px;border-radius:8px;font-weight:700;margin-top:14px}.cleanImageSlot{min-height:280px;border:2px dashed #a5b7af;border-radius:16px;background:#e9efeb;display:grid;place-items:center;color:#526b60;text-align:center;padding:20px}.cleanGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.cleanCard{background:#fff;border:1px solid #dce5df;border-radius:18px;padding:24px}.cleanCard .cleanImageSlot{min-height:190px}.cleanCard h3{font-size:1.4rem}.cleanDetails{border-top:1px solid #dce5df}.cleanFooter{background:#123b32;color:#fff;padding:30px max(24px,calc((100vw - 1100px)/2));display:flex;gap:20px;flex-wrap:wrap}.cleanFooter a{color:#fff}@media(max-width:720px){.cleanHero,.cleanGrid{grid-template-columns:1fr}.cleanHeader{align-items:flex-start;flex-direction:column}.cleanHero,.cleanSection{padding:42px 20px}.cleanImageSlot{min-height:220px}}`}</style>
<header className="cleanHeader"><a href="/" className="cleanBrand">AMRIT <span>AYURVEDA</span></a><nav><a href="#products">Products</a><a href="#details">Information</a><a href="#contact">Contact</a></nav></header>
<section className="cleanHero"><div><p>AMRIT AYURVEDA</p><h1>हमारे उत्पाद</h1><p>उत्पाद चुनें, कीमत देखें और अपनी डिलीवरी जानकारी देकर ऑर्डर करें।</p><a className="cleanButton" href="#products">उत्पाद देखें</a></div><div className="cleanImageSlot" role="img" aria-label="उत्पाद की तस्वीर के लिए खाली स्थान">उत्पाद की तस्वीर के लिए स्थान</div></section>
<section id="products" className="cleanSection"><h2>उत्पाद और कीमत</h2><div className="cleanGrid">{products.map(item=><article className="cleanCard" key={item.id}><div className="cleanImageSlot" role="img" aria-label={item.name+" की तस्वीर के लिए खाली स्थान"}>तस्वीर का स्थान</div><h3>{item.name}</h3><p>{item.detail}</p><p>Cash on Delivery: <strong>{item.cod}</strong><br/>Online payment: <strong>{item.online}</strong></p><a className="cleanButton" href={"/checkout?product="+item.id}>ऑर्डर करें</a></article>)}</div></section>
<section id="details" className="cleanSection cleanDetails"><h2>ऑर्डर की जानकारी</h2><p>ऑर्डर देते समय नाम, मोबाइल नंबर, पता और PIN कोड भरें। Cash on Delivery और ऑनलाइन भुगतान के विकल्प checkout पर दिखेंगे। सामग्री और उपयोग की जानकारी के लिए पैक पर दिया लेबल पढ़ें।</p><p>किसी प्रश्न के लिए ऑर्डर से पहले संपर्क करें।</p></section>
<footer id="contact" className="cleanFooter"><strong>Amrit Ayurveda</strong><a href="tel:+918290695226">+91 82906 95226</a><a href="https://wa.me/918290695226">WhatsApp</a><a href="/meta/policies">Privacy, shipping, refund &amp; terms</a></footer>
</main>}
